# Generated by Django 4.1.7 on 2023-03-08 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('company', models.TextField(blank=True)),
                ('date_applied', models.DateField()),
                ('method', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('dice', 'Dice'), ('company_website', 'Company Website'), ('other', 'Other')], max_length=15)),
                ('cover_letter', models.TextField(blank=True)),
                ('referral', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('first', models.BooleanField(default=False)),
                ('second', models.BooleanField(default=False)),
                ('third', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
