# Generated by Django 4.1.7 on 2023-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='method',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('otta', 'Otta'), ('company_website', 'Company Website'), ('other', 'Other')], max_length=15),
        ),
    ]
