# Generated by Django 4.1.7 on 2023-03-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cover_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='referral',
            field=models.BooleanField(default=False),
        ),
    ]
